version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb_dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: devuser
      MONGO_INITDB_ROOT_PASSWORD: devpass123
      MONGO_INITDB_DATABASE: dev_fastapi_db
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - dev-network

  mongodb_test:
    image: mongo:7.0
    container_name: mongodb_test
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass123
      MONGO_INITDB_DATABASE: test_fastapi_db
    volumes:
      - mongodb_test_data:/data/db
    networks:
      - dev-network

  fastapi_dev:
    build: .
    container_name: fastapi_dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://devuser:devpass123@mongodb_dev:27017/dev_fastapi_db?authSource=admin
      - DATABASE_NAME=dev_fastapi_db
      - ENVIRONMENT=development
    depends_on:
      - mongodb
    volumes:
      - ./app:/app
    networks:
      - dev-network

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dev-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: devuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: devpass123
      ME_CONFIG_MONGODB_URL: mongodb://devuser:devpass123@mongodb_dev:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - dev-network

volumes:
  mongodb_dev_data:
  mongodb_test_data:
  redis_data:

networks:
  dev-network:
    driver: bridge