version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: fastapi_db
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  fastapi:
    build: .
    container_name: fastapi_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/fastapi_db?authSource=admin
      - DATABASE_NAME=fastapi_db
    depends_on:
      - mongodb
    volumes:
      - ./app:/app
      - ./content.json:/app/content.json
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge